#!/bin/bash



clear
echo "START"
sleep 1s

ulang="y"

while [ $ulang = "y" ]
do

sudo apt update -y
sudo apt update -y
sudo apt update -y
sudo apt update -y


x=10
while [ $x -gt 0 ]
do
sleep 1s
clear
echo "Mulai ulang sisa Waktu anda $x Detik"
x=$(( $x - 1 ))
done



done
